version: "3.9"
   
services:
  app:
    build: .
    container_name: jobmonitor
    command: ./.docker/entrypoint.sh
    volumes:
      - .:/home/python/app
    ports:
      - "8007:8007"
  database:
    image: mysql:8.0
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwdb1
      MYSQL_DATABASE: django_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwdb2



